name: pawprint
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - attrs=19.3.0
  - black=19.10b0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - click=7.0
  - coverage=4.5.4
  - entrypoints=0.3
  - flake8=3.7.9
  - importlib_metadata=0.23
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpq=11.5
  - llvm-openmp=9.0.0
  - mccabe=0.6.1
  - more-itertools=7.2.0
  - mypy=0.740
  - mypy_extensions=0.4.3
  - ncurses=6.1
  - numpy=1.17.3
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.3
  - pathspec=0.6.0
  - pip=19.3.1
  - pluggy=0.12.0
  - psutil=5.6.5
  - psycopg2=2.8.4
  - py=1.8.0
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pyparsing=2.4.5
  - pytest=5.3.0
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - regex=2019.11.1
  - setuptools=42.0.1
  - six=1.13.0
  - sqlalchemy=1.3.11
  - sqlite=3.30.1
  - tk=8.6.10
  - toml=0.10.0
  - typed-ast=1.4.0
  - typing_extensions=3.7.4.1
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
